static char* asciiart = "\n"
	"    .:0WMMMMW0'                     :XWNXXO;                                                        \n"
	"   .oNMMMMMW0o..l;                  cNMMMMWo                                                        \n"
	"  ;kNMMMMWO:.  ,KXl.                .kMMMMX;  .odc:;.                                               \n"
	"  cNMMMMXl.     ;0NO,                lWMMWx. cKWMMMK;                                               \n"
	"  dWMMMK;        .xWXl.              cWMMK,  oWMMMM0'                                               \n"
	" '0MMMK;          .xWNc              oMMMx.  .:k0Okc.                                               \n"
	" cNMMK:            ,KM0'             lWMMd      .                                                   \n"
	" lWMMx.            .xMN:             cNMWo    ,ddc;'                          ...                   \n"
	" ;XMWo              dMN:             cNMWc   .xMMMMXl               .'     .cOKK0xc'':l:.  .....c,  \n"
	" .OMWo             .OMK,     ,kNKxdockWMX;    dMMMWk.    ,xOl.    ,0Nc    .xWMMMMWNNMMW0ldKNX0o,    \n"
	"  oWMk.            .OMd.   .lKWWMWKkONMMK,    dMMNXc     dMMx.     :NNc     ,0MMMMMW0odXWWMWWWMWd.  \n"
	"  ,KMN:  ..        .xNc    lNMMWk;. .xWMX;    ;KWKk;     cWMk;     ,KX:     .kMMMMWx. .OMW0c,,oXO.  \n"
	"   lNMO. .:.       ,K0'   .kMMWx.    cNMK,     :XKx,     ;KMMx.    ,KWd.    .xMMMWk.  .kMX:   .xX:  \n"
	"   .xWWd.         .dNo    .xMMX;     cNMO.     ,KKx,     .xWMKc'. .kWWK,     lWMMN:   .kMx.    cNd  \n"
	"    .kWWO:.      'xXk.     ,0WW0c'...dWMx.     .ON0:      ,0WMXdcl0NxdXO;.   cNMMK,   .kMd     .Ok. \n"
	"     .;xXWKkdllokXKl.       'dXMWNXKXNWMx.     .xWNo       .:d0XX0x;  ;x0c   ,KMMK,   .kWl      co. \n"
	"        .:oxOKKOd:.           'codxoc;oXk.      cNMk.          ...      .     c00l.    ';.          \n"
	"             ..                       .kK;      .oKx.                          ..                   \n"
	"                                       ,o'        .                                                 \n\n";
static char* asciitail =
	"              Free60.org XeLL RELOADED - Xenon Linux Loader\n\n";
